from ubuntu:16.04
RUN apt-get update && apt-get install -y apt-utils software-properties-common && apt-add-repository ppa:ubuntu-elisp/ppa -y
RUN apt-get update && apt-get install -y emacs-snapshot git curl wget vim
